config/routes.rb
Rails.application.routes.draw do
  # Static Pages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get 'provinces/:id/tax_rates', to: 'provinces#tax_rates', as: 'fetch_tax_rates'
  # Product Routes
  get 'products/:id', to: 'home#show', as: :product
  resources :products, only: [:index, :show]
  
  get 'on_sale', to: 'home#on_sale'
  get 'new_products', to: 'home#new_products'
  # Cart Routes
  post 'add_to_cart/:id', to: 'home#add_to_cart', as: :add_to_cart
  patch 'update_cart_item/:id', to: 'home#update_cart_item', as: :update_cart_item
  delete 'remove_from_cart/:id', to: 'home#remove_from_cart', as: :remove_from_cart
  get 'home/cart', to: 'home#cart', as: 'cart'

  # Orders Routes
  resources :orders, only: [:new, :create, :show]
  get 'orders', to: 'orders#index'
  get 'orders/:id/confirm_payment', to: 'orders#confirm_payment', as: 'confirm_payment_order'
  resources :orders do
    member do
      get 'confirm_payment'
    end
  end

  # Devise Routes for Users and Admins
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'profile', to: 'users#show'
  resources :users, only: [:show, :update]
  # Admin Namespace
  namespace :admin do
    get 'dashboard/index'
    resources :orders
    devise_for :admins, skip: :registrations
    root to: "products#index"
    resources :products
    resources :categories
    resources :provinces, only: [:index, :edit, :update]
  end

  # Category Routes
  resources :categories, only: [:index, :show]
  

  
  # Home/Index Route
  root 'home#index'
  get 'home/index', to: 'home#index', as: 'home_index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :initialize_cart, only: [:add_to_cart, :update_cart_item]

  def index
    @products = Product.all
    if params[:search].present?
      @products = @products.where('name LIKE :search OR description LIKE :search', search: "%#{params[:search]}%")
    end
    
    if params[:category_id].present?
      @products = @products.where(category_id: params[:category_id])
    end
    
    @products = @products.page(params[:page]).per(6) 
    @products = @products.where('created_at >= ?', 3.days.ago) if params[:new_products]
  end

  def new_products
    @new_products = Product.where('created_at >= ?', 3.days.ago)
    @new_products = @new_products.page(params[:page]).per(6)
  end
  
  def show
    @product = Product.find(params[:id])
  end

  def on_sale
    @products_on_sale = Product.where(on_sale: true).page(params[:page]).per(6)
  end

  

  def add_to_cart
    product_id = params[:id].to_i
    quantity = params[:quantity].to_i || 1
  
   
    session[:cart] = [] unless session[:cart].is_a?(Array)
  
    item = session[:cart].find { |i| i["product_id"] == product_id }
  
    if item

      item["quantity"] += quantity
    else
      # Otherwise, add a new item to the cart
      session[:cart] << { "product_id" => product_id, "quantity" => quantity }
    end
  

    redirect_to cart_path, notice: "Product added to cart!"
  end
  

  def update_cart_item
    product_id = params[:id].to_i
    new_quantity = params[:quantity].to_i
  
    item = session[:cart].find { |i| i["product_id"] == product_id }
    if item
      item["quantity"] = new_quantity
      flash[:notice] = "Quantity updated."
    end
  
    redirect_to cart_path
  end

  
  
  def remove_from_cart
    product_id = params[:id].to_i

    session[:cart].delete_if { |item| item["product_id"] == product_id }

    redirect_to cart_path, notice: 'Item removed from cart.'
  end
  
  private

  def initialize_cart
    session[:cart] ||= []
  end

end

app/views/home/cart.html.erb
<%= render 'layouts/clientNav' %>
<div class="container mt-5">
  <h2>Shopping Cart</h2>
  <h6>Customer Name: <%= current_user.customer.name %></h6>
  <% if cart.blank? %>
    <div class="alert alert-info" role="alert">
      Your shopping cart is empty. Start shopping now!
    </div>
  <% else %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Total</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
        <% cart.each do |item| %>
          <tr>
            <td><%= item[:product].name %></td>
            <td>
              <%= form_with url: update_cart_item_path(id: item[:product].id), method: :patch, local: true do |f| %>
                <div class="input-group">
                  <%= f.number_field :quantity, value: item[:quantity], min: 1, class: 'form-control', style: 'width: 70px;' %>
                  <div class="input-group-append">
                    <%= f.submit "Update", class: "btn btn-info" %>
                  </div>
                </div>
              <% end %>
            </td>
            <td><%= number_to_currency(item[:product].price) %></td>
            <td><%= number_to_currency(item[:quantity] * item[:product].price) %></td>
            <td>
            <%= button_to 'Remove', remove_from_cart_path(id: item[:product].id), method: :delete, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="text-right">
      <h3>Total: <%= number_to_currency(cart.sum { |item| item[:quantity] * item[:product].price }) %></h3>
      <%= link_to 'Checkout', new_order_path, class: 'btn-custom-primary' %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render 'layouts/clientNav' %>
<%= render 'layouts/hero' %>
<div class="container mt-5">
<%= form_with url: home_index_path, method: :get, local: true, class: 'form-inline justify-content-center' do |form| %>
  <div class="form-row align-items-center">
    <div class="col-auto">
      <%= form.text_field :search, placeholder: "Search for products", value: params[:search], class: 'form-control mb-2' %>
    </div>
    <div class="col-auto">
      <%= form.collection_select :category_id, Category.all, :id, :name, { include_blank: "All Categories" }, { class: 'form-control mb-2' } %>
    </div>
    <div class="col-auto">
      <%= form.submit 'Search', class: 'btn-custom-primary' %>
    </div>
  </div>
<% end %>
<h2 class="text-center mb-4">Explore Products</h2>
<div class="row text-center mb-4">
  <div class="col-md-4 mb-3">
    <%= link_to categories_path, class: 'btn btn-lg btn-info btn-block' do %>
      <i class="fa fa-tags"></i> Categories
    <% end %>
  </div>
  <div class="col-md-4 mb-3">
    <%= link_to on_sale_path, class: 'btn btn-lg btn-info btn-block' do %>
      <i class="fa fa-percent"></i> On Sale
    <% end %>
  </div>
  <div class="col-md-4 mb-3">
    <%= link_to root_path(new_products: true), class: 'btn btn-lg btn-info btn-block' do %>
      <i class="fa fa-newspaper-o"></i> New Products
    <% end %>
  </div>
   
  </div>


  <% if @products.empty? %>
    <div class="alert alert-info text-center">
      <strong>No products found.</strong>
    </div>
  <% else %>
    <div class="row">
  
  <%= render partial: 'layouts/product_card', collection: @products, as: :product %>
 
    </div>
  <% end %>
  
  <%= paginate @products %>
</div>

app/views/home/new_products.html.erb
<div class="container mt-5">
  <h1>New Products</h1>
  <div class="row">

      <%= render partial: 'layouts/product_card', collection:  @new_products, as: :product %>




  </div>
  <%= paginate @new_products %>
</div>

app/views/home/on_sale.html.erb
<%= render 'layouts/clientNav' %>

<div class="container mt-5">
  <h1>Products On Sale</h1>
  <div class="row">
    

      <%= render partial: 'layouts/product_card', collection: @products_on_sale, as: :product %>

  </div>
</div>

app/views/home/show.html.erb
<%= render 'layouts/clientNav' %>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <div class="card mb-4 shadow-sm">
        <div class="row g-0">
          <div class="col-md-6">
            <% if @product.image.attached? %>
              <%= image_tag(@product.image, class: 'img-fluid rounded-start') %>
            <% else %>
              <img src="https://via.placeholder.com/500x300" class="img-fluid rounded-start" alt="Product Image">
            <% end %>
          </div>
          <div class="col-md-6">
  <div class="card-body">
    <div class="card-header bg-light">
      <h1 class="display-4"><%= @product.name %></h1>
      <p> <%= @product.category.name if @product.category.present? %></p>
    </div>
    <div class="p-3">
      <p class="lead"><%= @product.description %></p>
      
      <p> <%= @product.ingredients %></p>
      <p class="h4"> <%= number_to_currency(@product.price) %></p>
    </div>

    <%= form_with url: add_to_cart_path(id: @product.id), method: :post, class: 'mt-4' do |form| %>
      <div class="form-group row">
        <%= form.label :quantity, 'Quantity', class: 'col-sm-4 col-form-label' %>
        <div class="col-sm-3">
          <%= form.number_field :quantity, value: 1, min: 1, class: 'form-control', required: true %>
        </div>
      </div>
      <%= form.submit 'Add to Cart', class: ' btn-custom-primary' %>
      <%= link_to 'Back to products', root_path, class: ' btn-custom-secondary' %>
    <% end %>

  
  </div>
</div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>