config/routes.rb
Rails.application.routes.draw do
  # Static Pages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get 'provinces/:id/tax_rates', to: 'provinces#tax_rates', as: 'fetch_tax_rates'
  # Product Routes
  get 'products/:id', to: 'home#show', as: :product
  resources :products, only: [:index, :show]
  
  get 'on_sale', to: 'home#on_sale'
  get 'new_products', to: 'home#new_products'
  # Cart Routes
  post 'add_to_cart/:id', to: 'home#add_to_cart', as: :add_to_cart
  patch 'update_cart_item/:id', to: 'home#update_cart_item', as: :update_cart_item
  delete 'remove_from_cart/:id', to: 'home#remove_from_cart', as: :remove_from_cart
  get 'home/cart', to: 'home#cart', as: 'cart'

  # Orders Routes
  resources :orders, only: [:new, :create, :show]
  get 'orders', to: 'orders#index'
  get 'orders/:id/confirm_payment', to: 'orders#confirm_payment', as: 'confirm_payment_order'
  resources :orders do
    member do
      get 'confirm_payment'
    end
  end

  # Devise Routes for Users and Admins
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'profile', to: 'users#show'
  resources :users, only: [:show, :update]
  # Admin Namespace
  namespace :admin do
    get 'dashboard/index'
    resources :orders
    devise_for :admins, skip: :registrations
    root to: "products#index"
    resources :products
    resources :categories
    resources :provinces, only: [:index, :edit, :update]
  end

  # Category Routes
  resources :categories, only: [:index, :show]
  

  
  # Home/Index Route
  root 'home#index'
  get 'home/index', to: 'home#index', as: 'home_index'
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    
    validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_category, only: [:show, :edit, :update, :destroy]
  
    def index
      @categories = Category.all
    end
  
    def show
    end
  
    def new
        @category = Category.new
    end
  
    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_url, notice: 'Category was successfully created.'
      else
        render :new
      end
    end
    
  
    def edit
    end
  
    def update
      if @category.update(category_params)
        redirect_to admin_categories_url, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end
    
  
    def destroy
      @category.destroy
      redirect_to admin_categories_url, notice: 'Category was successfully destroyed.'
    end
  
    private
      def set_category
        @category = Category.find(params[:id])
      end
  
      def category_params
        params.require(:category).permit(:name, :description)
      end
  end
  

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
      @categories = Category.all
    end
  
    
    def show
      @category = Category.find(params[:id])
      @products = @category.products
    end
  end
  

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<%= render 'layouts/adminNav' %>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow">
        <div class="card-header">
          <h1>Edit Category</h1>
        </div>
        <div class="card-body">
          <%= form_with(model: [:admin, @category], local: true, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
            <% if @category.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
                <ul>
                  <% @category.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= form.label :name, class: 'form-label' %>
              <%= form.text_field :name, class: 'form-control' %>
            </div>
        
            <div class="form-group">
              <%= form.label :description, class: 'form-label' %>
              <%= form.text_area :description, class: 'form-control' %>
            </div>
        
            <div class="actions  mt-4">
              <%= form.submit class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        <div class="card-footer bg-transparent">
          <%= link_to 'Back to List', admin_categories_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<%= render 'layouts/adminNav' %>

<div class="container mt-4">
  <h1>Categories</h1>
  <%= link_to 'New Category', new_admin_category_path, class: 'btn btn-success mb-3' %>

  <div class="table-responsive">
    <table class="table table-hover">
      <thead class="thead-dark"> <!-- Changed from thead-light to thead-dark for consistency -->
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th colspan="2" scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= category.description %></td>
            <td><%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm' %> <!-- Adjust button classes as needed --></td>
            <td>
              <%= button_to 'Destroy', [:admin, category], method: :delete, form: { class: 'd-inline' }, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %> <!-- Adjust button classes as needed -->
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/categories/new.html.erb
<%= render 'layouts/adminNav' %>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow">
        <div class="card-header">
          <h1>New Category</h1>
          
        </div>

        <div class="card-body">
          <%= form_with(model: [:admin, @category], local: true, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
            <% if @category.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
                <ul>
                  <% @category.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= form.label :name, class: 'form-label' %>
              <%= form.text_field :name, class: 'form-control' %>
            </div>
        
            <div class="form-group">
              <%= form.label :description, class: 'form-label' %>
              <%= form.text_area :description, class: 'form-control' %>
            </div>
        
            <div class="actions  mt-4">
              <%= form.submit class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        <div class="card-footer bg-transparent">
          <%= link_to 'Back to List', admin_categories_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>