config/routes.rb
Rails.application.routes.draw do
  # Static Pages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get 'provinces/:id/tax_rates', to: 'provinces#tax_rates', as: 'fetch_tax_rates'
  # Product Routes
  get 'products/:id', to: 'home#show', as: :product
  resources :products, only: [:index, :show]
  
  get 'on_sale', to: 'home#on_sale'
  get 'new_products', to: 'home#new_products'
  # Cart Routes
  post 'add_to_cart/:id', to: 'home#add_to_cart', as: :add_to_cart
  patch 'update_cart_item/:id', to: 'home#update_cart_item', as: :update_cart_item
  delete 'remove_from_cart/:id', to: 'home#remove_from_cart', as: :remove_from_cart
  get 'home/cart', to: 'home#cart', as: 'cart'

  # Orders Routes
  resources :orders, only: [:new, :create, :show]
  get 'orders', to: 'orders#index'
  get 'orders/:id/confirm_payment', to: 'orders#confirm_payment', as: 'confirm_payment_order'
  resources :orders do
    member do
      get 'confirm_payment'
    end
  end

  # Devise Routes for Users and Admins
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'profile', to: 'users#show'
  resources :users, only: [:show, :update]
  # Admin Namespace
  namespace :admin do
    get 'dashboard/index'
    resources :orders
    devise_for :admins, skip: :registrations
    root to: "products#index"
    resources :products
    resources :categories
    resources :provinces, only: [:index, :edit, :update]
  end

  # Category Routes
  resources :categories, only: [:index, :show]
  

  
  # Home/Index Route
  root 'home#index'
  get 'home/index', to: 'home#index', as: 'home_index'
end

app/views/layouts/_adminNav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'SOAPPED', home_index_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if admin_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Products', admin_products_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Categories', admin_categories_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Orders', admin_orders_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Provinces', admin_provinces_path, class: 'nav-link' %>
          </li>
          
          
          <li class="nav-item">
            <%= button_to 'Logout', destroy_admin_session_path, method: :delete, class: 'btn btn-primary' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Admin Login', new_admin_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/_clientNav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom" >
<%= link_to root_path, class: 'navbar-brand' do %>
  <%= image_tag('soapPED.png', alt: 'Sopped Logo', class:"logo") %>
<% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Cart', cart_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Orders', orders_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", profile_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, form_class: "d-inline", class: "btn btn-link nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="breadcrumbs-container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <% generate_breadcrumbs.each do |breadcrumb| %>
        <% if request.path == breadcrumb[:path] %>
          <li class="breadcrumb-item active" aria-current="page"><%= breadcrumb[:title] %></li>
        <% else %>
          <li class="breadcrumb-item"><%= link_to breadcrumb[:title], breadcrumb[:path] %></li>
        <% end %>
      <% end %>
    </ol>
  </nav>
</div>

app/views/layouts/_hero.html.erb
<div class="hero-header text-center text-white py-5" style="background-image: url('https://images.unsplash.com/photo-1629732097571-b042b35aa3ed?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'); background-size: cover; background-position: center;">
  <div class="container">
    <h1 class="display-4 font-weight-bold">Welcome to SOAPPED</h1>
    <p class="lead">Explore our vast collection of Skin Care Products.</p>
  </div>
</div>

app/views/layouts/_product_card.html.erb
<div class="col-md-4 mb-4">
  <div class="card h-100 shadow-sm">
    <% if product.image.attached? %>
      <%= image_tag(product.image, class: 'card-img-top') %>
    <% else %>
      <img src="https://via.placeholder.com/300x300" alt="No image available" class="card-img-top">
    <% end %>
    <div class="card-body d-flex flex-column">
      <h5 class="card-title"><%= product.name %></h5>
      <p class="card-text"><%= truncate(product.description, length: 100) %></p>
      <div class="mt-auto">
        <h6 class="card-subtitle mb-2 text-muted">Price: <%= number_to_currency(product.price) %></h6>
        <%= link_to 'View', product_path(product), class: 'btn-custom-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcomSahibpreet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
    .hero-header {
  height: 75vh; 
  display: flex;
  align-items: center;
  justify-content: center;
  background-attachment: fixed;
}

.hero-header h1,
.hero-header p {
  text-shadow: 1px 1px 8px rgba(0, 0, 0, 0.7);
}
    </style>
  </head>
  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  
    <%= yield %>
  </body>
</html>